[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
exclude_file = []
follow_symlink = true
delay = 1000
stop_on_error = true

[log]
time = true
